---
# playbook.yml

- name: Ping all servers in inventory
  hosts: all
  tasks:
    - name: Ping hosts
      ping:
      tags:
        - ping 
        - always

- name: Install Docker in all servers
  hosts: all
  become: true
  roles:
    - docker

- name:  Setup the Jenkins
  hosts: jenkins_servers
  become: true
  roles:
    - role: docker
      vars:
        docker_user: jenkins
      tags: [docker]

    - role: jenkins
      tags: [jenkins]

- name: Setup K8s Cluster and Install ArgoCD
  hosts: k8s_cluster
  become: yes
  roles:
    - role: k8s
      tags: [k8s]
    - role: argocd
      tags: [argocd]

...
