# tasks file for argocd_prerequisities_install

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_dependencies }}"

- name: Install Argo CLI
  shell: |
    curl -sSL -o /usr/local/bin/argo https://github.com/argoproj/argo/releases/latest/download/argo-linux-amd64
    chmod +x /usr/local/bin/argo
  args:
    executable: /bin/bash
  register: argocd_install
