---
# tasks file for ansible/roles/argocd/main.yml

- name: ArgoCD installation
  import_tasks: argocd_install.yml
  tags:
    - argocd_install
    - install

- name: ArgoCD workflow creation
  import_tasks: argocd_create_workflow.yml
  tags: 
    - argcd_create_workflow
    - create_workflow

- name: Uninstall argocd
  import_tasks: argocd_uninstall.yaml
  tags:
    - never
...