---
# tasks file for ansible/roles/argocd/main.yml

- name: Install Argo CD dependances
  import_tasks: argocd_prerequisistes_install.yml
  tags:
    - argocd_install
    - install
  when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'
  
- name: Install Argo CD
  import_tasks: argocd_install.yml
  tags:
    - argocd_install
    - install
  when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

- name: Create Argo CD workflow
  import_tasks: argocd_create_workflow.yml
  tags: 
    - argcd_create_workflow
    - create_workflow
  when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

- name: Uninstall argocd
  import_tasks: argocd_uninstall.yaml
  tags:
    - argocd_uninstall
    - uninstall
    - never
  when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'
...
