###################################################################################
# Description:
###################################################################################
# With this workflow in place, every time you push changes to the specified branch, 
# the workflow will run. It will build the Docker image, login to Docker Hub 
# using your credentials, tag the image, and push it to Docker Hub.

name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: mk-devops-webapp
      DOCKER_CONTAINER_NAME: my-devops-webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build Job
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .
  
      # Run and Test docker container Job
      - name: Run and Test Docker container
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:latest npm test
        # docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} -p 3000:3000 ${{ env.DOCKER_IMAGE_NAME }}:latest
  
      # - name: Wait for container to start
      #   run: sleep 10
  
      # - name: Test container accessibility
      #   run: |
      #       curl -L http://localhost:3000
  
      # - name: Stop and remove container
      #   run: docker stop ${{ env.DOCKER_CONTAINER_NAME }} && docker rm ${{ env.DOCKER_CONTAINER_NAME }}

  # Deployment Stage
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image to DockerHub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
