name: Build, Test and Deploy docker webapp image

on:
  push:
    tags:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t my-devops-webapp .

    - name: Run test
      run: |
        # run the container and test its behavior
        docker run --rm --name my-devops-webapp curl http://localhost:8080
        
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          # Tag with the created tag name and push to Docker Hub
          docker tag my-devops-webapp ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-webapp:${{ github.ref }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-webapp:${{ github.ref }}
